import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "bg-red-500",
    "bg-yellow-300",
    "bg-yellow-700",
    "bg-gray-700",
    "bg-green-500",
    "bg-purple-500",
    "bg-red-600",
    "text-red-500",
    "text-yellow-500",
    "text-orange-500",
    "text-amber-500",
    "text-lime-500",
    "text-green-500",
    "text-emerald-500",
    "text-teal-500",
    "text-cyan-500",
    "text-sky-500",
    "text-blue-500",
    "text-indigo-500",
    "text-violet-500",
    "text-purple-500",
    "text-fuchsia-500",
    "text-pink-500",
    "text-rose-500",
    "border-red-500",
    "border-yellow-500",
    "border-orange-500",
    "border-amber-500",
    "border-lime-500",
    "border-green-500",
    "border-emerald-500",
    "border-teal-500",
    "border-cyan-500",
    "border-sky-500",
    "border-blue-500",
    "border-indigo-500",
    "border-violet-500",
    "border-purple-500",
    "border-fuchsia-500",
    "border-pink-500",
    "border-rose-500",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [require("daisyui")],
};
export default config;
